# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('iname', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameResultsDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action1', models.CharField(max_length=10)),
                ('result1', models.CharField(max_length=10)),
                ('action2', models.CharField(max_length=10)),
                ('result2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player1Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.IntegerField()),
                ('actionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Player2Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.IntegerField()),
                ('actionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('iname', models.IntegerField()),
            ],
        ),
    ]
